// <auto-generated />
using System;
using Metamask.Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Metamask.Migrations
{
    [DbContext(typeof(MetamaskSqlContext))]
    [Migration("20190320072925_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Metamask.Data.Sql.PageMaskDto", b =>
                {
                    b.Property<Guid>("PageMaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDateUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(160);

                    b.Property<string>("Image")
                        .HasMaxLength(2083);

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2083);

                    b.Property<string>("Title")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdateDateUtc");

                    b.HasKey("PageMaskId");

                    b.ToTable("PageMasks");
                });
#pragma warning restore 612, 618
        }
    }
}
