// <auto-generated />
using System;
using Metamask.Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Metamask.Migrations
{
    [DbContext(typeof(MetamaskSqlContext))]
    [Migration("20200112030434_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Metamask.Data.Sql.PageMaskDto", b =>
                {
                    b.Property<Guid>("PageMaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("page_mask_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDateUtc")
                        .HasColumnName("create_date_utc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("character varying(160)")
                        .HasMaxLength(160);

                    b.Property<string>("Image")
                        .HasColumnName("image")
                        .HasColumnType("character varying(2083)")
                        .HasMaxLength(2083);

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnName("target_url")
                        .HasColumnType("character varying(2083)")
                        .HasMaxLength(2083);

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdateDateUtc")
                        .HasColumnName("update_date_utc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PageMaskId")
                        .HasName("pk_page_masks");

                    b.ToTable("page_masks");
                });
#pragma warning restore 612, 618
        }
    }
}
